---
meta:
  name:    safe
  release: Safe
  target:  sw
  url:     https://ci.vsphere.starkandwayne.com

  initial_version: 0.0.5

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  starkandwayne
    repo:   safe
    private_key:  (( vault "secret/pipelines/safe/github:private" ))
    access_token: (( vault "secret/pipelines/safe/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/safe/slack:webhook" ))
    channel: '#botspam'
